apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  generation: 4
  name: debezium-kafka-cluster
  namespace: default
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    listeners:
      external:
        authentication:
          type: tls
        type: route
      plain: {}
      tls: {}
    replicas: 1
    storage:
      type: ephemeral
    version: ${version.kafka}
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
